# Generated by Django 3.1.6 on 2021-04-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210419_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
