# Generated by Django 3.2 on 2021-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210419_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_limit',
            field=models.IntegerField(null=True),
        ),
    ]
