# Generated by Django 3.2 on 2021-05-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210504_1329'),
        ('main', '0006_merge_20210504_2103'),
    ]

    operations = [
    ]
