# Generated by Django 3.1.6 on 2021-05-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210504_2128'),
        ('main', '0006_merge_20210504_2103'),
    ]

    operations = [
    ]
