# Generated by Django 3.2 on 2021-05-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20210506_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Captain', to='main.league'),
        ),
    ]
