# Generated by Django 3.1.6 on 2021-05-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210509_1925'),
        ('main', '0008_auto_20210506_2147'),
    ]

    operations = [
    ]
