# Generated by Django 3.2 on 2021-05-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_team_player_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.TextField(max_length=16, null=True),
        ),
    ]
