# Generated by Django 3.1.6 on 2021-05-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210427_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
