# Generated by Django 3.1.7 on 2021-05-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210427_0001'),
        ('main', '0005_auto_20210427_2323'),
    ]

    operations = [
    ]
