# Generated by Django 3.2 on 2021-05-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210506_2107'),
        ('main', '0007_merge_20210506_1353'),
    ]

    operations = [
    ]
