# Generated by Django 3.2 on 2021-05-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210507_0021'),
        ('main', '0008_merge_20210506_1754'),
    ]

    operations = [
    ]
