# Generated by Django 3.1.7 on 2021-05-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_team_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='player_limit',
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Captain', to='main.account'),
        ),
    ]
