# Generated by Django 3.1.7 on 2021-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_league_player_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='My Team', max_length=16),
        ),
    ]
