# Generated by Django 3.1.7 on 2021-05-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20210509_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_limit',
        ),
    ]
