# Generated by Django 3.2 on 2021-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.TextField(blank=True, max_length=16, null=True),
        ),
    ]
